default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: askme_development

test:
  <<: *default
  database: askme_test

production:
  <<: *default
  username: b41f6157db40bd
  password: 40dac1cb
  host: us-cdbr-iron-east-05.cleardb.net
  database: heroku_b6a0c4a452efd3a
